# Generated by Django 3.0.8 on 2020-07-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
